---           
layout: post
title: Dubnotes: Basic Tests
date: 2012-02-05 19:11:24 UTC
updated: 2012-02-05 19:11:24 UTC
comments: false
categories: Dubnotes
---

Before redesigning the program, I am going to write some testcode on the current state of the app.<b></b><br /><a name='more'></a><b> &nbsp; </b><br /><br /><b>Refactoring Dubnotes</b><br /><br /><div style="text-align: center;">The complete code can be found here: <a href="http://github.com/dubspeed/dubnotes">http://github.com/dubspeed/dubnotes</a></div><br />Revisiting the codebase after a long time gives the chance to re-learn the code and guess the intentions of the program from a more distant point of view.<br /><br />I split the review into multiple parts, starting with the main application code in dubnotes.py and working from there down to the frontend code.<br /><br />Since I want to rewrite the code without breaking it, I am going to write a huge set of tests first, before I touch the code.<br /><br /><b>Refactoring Part I: Starting with tests </b><br /><br />When you take a look at the main file <a href="https://github.com/dubspeed/dubnotes/blob/74138861a6a3fcda7385a4c56d3d9990731af2af/dubnotes.py">dubnotes.py</a>, you spot the huge MainPage Class, which is a mess.<br /><br />The class deals with a lot of stuff at the same time:<br /><ul><li>controls the views (edit / listview) and provides functionality for editing the notes</li><li>controls the state of the application (get / post) and the user state</li><li>does authentication</li></ul>Thats too much, violating the SRP <a href="http://en.wikipedia.org/wiki/Single_responsibility_principle">[1]</a>, so we should split things up into separate classes and modules. But before that we have to make sure we won´t break the code, so we should write unit tests at first.<br /><br />So, how do we write unit tests for this class?<br /><br /><br /><br /><br /><b>Getting things to work</b><br /><br />Let´s first get the app running inside the development environment. I have downloaded and installed the Appengine SDK from <a href="http://code.google.com/intl/en/appengine/">[2]</a> and start the appengine server with the command:<br /><br /><pre class="brush: py;">path_to_appengine/dev_appserver.py dubnotes --clear_datastore</pre><br />This starts a webserver on<br /><br /><pre class="brush: py;">http://localhost:8080<br /></pre><br />Browsing there presents me:<br /><br /><div style="font-family: &quot;Courier New&quot;,Courier,monospace; text-align: center;"><span style="font-size: x-small;">Authentication error.</span></div><br />That is from dubnotes.py code, line 113:<br /><br /><pre class="brush: py;">def get(self):<br />&nbsp; try:<br />&nbsp;&nbsp;&nbsp;&nbsp; config, db_client, token, user = self.quick_auth()<br />&nbsp; except:<br />&nbsp;&nbsp;&nbsp;&nbsp; self.response.out.write('Authentication error.')<br />&nbsp;&nbsp;&nbsp;&nbsp; return<br /></pre><br />The reason is: I have to provide a consumer key and a consumer secrect from the Dropbox web-API in dubnotes.ini first, before the app can request tokens from the Dropbox website.<br /><br />The app actually browses the Dropbox website, tries to authenticate and fails. I do not want that inside my development environment for two reasons:<br /><ol><li>The state of the Dropbox website is unpredictable to me, it may be broken or offline</li><li>I do not want to develop against live data in my dropbox.</li></ol>So I decide to decouple the Dropbox integration from Dubnotes, and to create a Fake-Dropbox for my tests. <br /><br /><b>Preparing to decouple the application</b> <br /><br />What does Dopnots actually want from Dropbox, which API calls are made?<br /><br />I decided to analyze the working online version first, and see how the application behaves against Dropbox.<br /><br />So, where does "authentication error" come from? It comes from the fact that when my request runs into quick_auth, it first tries to connect to dropbox.com and get an authorization from there. The connect fails and the exception occurs (besides, the error-handling needs improvement).<br /><br />After I put in the consumer_key and secret in dubnotes.ini (provided to my from Dropbox´s Developer site) and reload http://localhost:8080, I get to see the Dropbox Login Page with the message on top:<br /><br />An application wants to link to your Dropbox. Please login or register.<br /><br />So the first test I write should test for the correct redirection to dropbox.com when the user connects without any info in the key-value store (the user is unknown to us):<br /><br /><pre class="brush: py;">import unittest<br />import httplib<br />import string<br /><br />class mustRedirectToDropbox(unittest.TestCase):<br />&nbsp;&nbsp;&nbsp; def runTest(self):<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; httpconnection = httplib.HTTPConnection('localhost:8080')<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; httpconnection.request("GET", "/")<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; response = httpconnection.getresponse()<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; assert response.status == 302, "expect 302 == FOUND"<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; assert isinstance(response, httplib.HTTPResponse), "wrong or missing http-Response"<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; assert string.find(self.response.msg.get("location", ""), "https://www.dropbox.com/0/oauth/authorize") &gt;= 0, "wrong website"<br /></pre><br />The status code 302 in the answer of the request is a redirect, which indicates that there is a "location" header-message with a new URL.<br /><br />For our testing purpose there should be a method to check weather we already have a user in our database and therefore the redirect to dropbox.com is correct or not. There is no such function in the app.<br /><br />The next step is to authenticate with the app. Assuming we are authenticated, we would expect a different website to show up when we browse to http://localhost:8080<br /><br /><pre class="brush: py;">class mustShowDubnotesWhenAuthenticated(unittest.TestCase):<br />&nbsp;&nbsp;&nbsp; def runTest(self):<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; httpconnection = httplib.HTTPConnection('localhost:8080')<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; httpconnection.request("GET", "/")<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; response = httpconnection.getresponse()<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; assert isinstance(response, httplib.HTTPResponse), "wrong or missing http-Response"<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; assert string.find(response.read(), "Dub Notes") &gt;= 0, "wrong website"<br /></pre><br />This looks the same as above so we can put them together:<br /><br /><pre class="brush: py;">class LandingPageTestCase(unittest.TestCase):<br />&nbsp;&nbsp;&nbsp; def setUp(self):<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; self.httpconnection = httplib.HTTPConnection('localhost:8080')<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; self.httpconnection.request("GET", "/")<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; self.response = self.httpconnection.getresponse()<br />&nbsp;&nbsp;&nbsp; def testCorrectHTTPRequest(self):<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; assert isinstance(self.response, httplib.HTTPResponse), "wrong or missing http-Response"<br />&nbsp;&nbsp;&nbsp; def testRedirectToDropboxWhenUnauthenticated(self):<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; assert self.response.status == 302, "expect 302 == FOUND"<br />&nbsp;&nbsp; &nbsp;&nbsp; assert string.find(self.response.msg.get("location", ""), "https://www.dropbox.com/0/oauth/authorize") &gt;= 0, "wrong website"<br />&nbsp;&nbsp;&nbsp; def testDubnotesLandingPage(self):<br />&nbsp;&nbsp; &nbsp;&nbsp; assert self.response.status == 200, "expect 200 == OKAY"<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; assert string.find(self.response.read(), "Dub Notes") &gt;= 0, "wrong website"<br />&nbsp;&nbsp; <br />unittest.makeSuite(LandingPageTestCase, "test")<br /></pre><br />The app stores my authentication token and secret, so every time I log back in, I am returning to the Dubnotes page instead of the dropbox login page. At the same time the login is successfully, I get an URL like this:<br /><br /><div style="font-family: &quot;Courier New&quot;,Courier,monospace;"><span style="font-size: x-small;">http://localhost:8080/?uid=3xxxxxxx8&amp;oauth_token=uyyyyyyyyyyy9</span></div><br />"uid" is the unique user-id from my dropbox account, and the oauth-token identifies my session (this is needed to query the user id from dropbox).<br />These guys are passed around in the app a whole lot. Having them in public is also a huge security problem, i´ll have to deal with later.<br /><br />The problem is that one of my tests "RedirectToDropboxWhenUnauthenticated" or "DubnotesLandingPage" always fails, so I rewrite the code:<br /><br /><pre class="brush: py;">class LandingPageTestCase(unittest.TestCase):<br />&nbsp;&nbsp;&nbsp; def requestPage(self, url_part):<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; self.httpconnection.request("GET", url_part)<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; return self.httpconnection.getresponse()<br />&nbsp;&nbsp;&nbsp; def setUp(self):<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; self.httpconnection = httplib.HTTPConnection('localhost:8080')<br />&nbsp;&nbsp;&nbsp; def testCorrectHTTPRequest(self):<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; response = self.requestPage("/")<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; assert isinstance(response, httplib.HTTPResponse), "wrong or missing http-Response"<br />&nbsp;&nbsp;&nbsp; def testRedirectToDropboxWhenUnauthenticated(self):<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; response = self.requestPage("/")<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; assert response.status == 302, "expect 302 == FOUND"<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; assert string.find(response.msg.get("location", ""), "https://www.dropbox.com/0/oauth/authorize") &gt;= 0, "wrong website"<br />&nbsp;&nbsp;&nbsp; def testDubnotesLandingPage(self):<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; response = self.requestPage("/?uid=3xxxxxx8&amp;oauth_token=uyyyyyyyyyy9")<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; assert response.status == 200, "expect 200 == OKAY"<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; assert string.find(response.read(), "Dub Notes") &gt;= 0, "wrong website"<br /></pre><br />Here is what I learned:<br />- When the browser connects via "/" - without any parameters, the app assumes that the user is unauthenticated and triggers authentication<br />- When I connect via "/?uid=3xxxxxx8&amp;oauth_token=uyyyyyyyyyy9", it is assumed that we are authentcated, and the app happily accesses dropbox without re-authentication<br /><br />But there is more:<br />When I log on to my dropbox, I can remove the app from the list of authenticated apps. If I do so, and try to connect the app fails with a dump:<br /><br /><div style="font-family: &quot;Courier New&quot;,Courier,monospace;"><span style="font-size: x-small;">Traceback (most recent call last):</span></div><div style="font-family: &quot;Courier New&quot;,Courier,monospace;"><span style="font-size: x-small;">&nbsp; File "/Users/michael/Documents/dubnotes_entwicklungs_pakete/google_appengine/google/appengine/ext/webapp/__init__.py", line 700, in __call__</span></div><div style="font-family: &quot;Courier New&quot;,Courier,monospace;"><span style="font-size: x-small;">&nbsp;&nbsp;&nbsp; handler.get(*groups)</span></div><div style="font-family: &quot;Courier New&quot;,Courier,monospace;"><span style="font-size: x-small;">&nbsp; File "/Users/michael/Dropbox/sync/workspace/dubnotes/dubnotes.py", line 126, in get</span></div><div style="font-family: &quot;Courier New&quot;,Courier,monospace;"><span style="font-size: x-small;">&nbsp;&nbsp;&nbsp; self.list_view(config, db_client, token, user)</span></div><div style="font-family: &quot;Courier New&quot;,Courier,monospace;"><span style="font-size: x-small;">&nbsp; File "/Users/michael/Dropbox/sync/workspace/dubnotes/dubnotes.py", line 162, in list_view</span></div><div style="font-family: &quot;Courier New&quot;,Courier,monospace;"><span style="font-size: x-small;">&nbsp;&nbsp;&nbsp; 'files': [['/?uid=' + user.uid + '&amp;oauth_token=' + token.req_key + '&amp;action=edit&amp;get=' + cgi.escape(x["path"]), os.path.basename(x["path"])] for x in resp.data['contents'] if not x['is_dir']],</span></div><div style="font-family: &quot;Courier New&quot;,Courier,monospace;"><span style="font-size: x-small;">KeyError: 'contents'</span></div><br />Bad thing. <br /><br />When I re-authenticate the app in dropbox (visiting the app with "/"), i get a new URL with a new oauth-Token for my user, but it still fails!<br /><br /><div style="font-family: &quot;Courier New&quot;,Courier,monospace;"><span style="font-size: x-small;">http://localhost:8080/?uid=3xxxxxxx8&amp;oauth_token=91yyyyyyyyyy32</span></div><br />The problem vanishes as soon as I clear the datastore via dev_appserver.py --clear_datastore <br /><br />I guess the old user data in the datastore is the problem, it screws the process.<br /><br /><b>Conclusion</b><br /><br />Writing some basic and simple tests on my applications gives me a new inside look on my code, as supposed&nbsp; :)<br /><br />I can nailed down some of the functionality in form of unittests and while doing this, i found complete new bug, which will need some fixing when the refactoring is done.&nbsp; <br /><br /><b>What´s next</b><br /><br />To proceed writing good tests on the existing codes, we need to de-couple the existing module from its surrounding world.<br /><br /><b>References</b><br />[1] http://en.wikipedia.org/wiki/Single_responsibility_principle<br />[2] http://code.google.com/intl/en/appengine/